import tensorflow as tf
# Constants
RANDOM_STATE_PER_RUN = [42, 9, 23, 101, 13]
RANDOM_STATE = 42 # random state for model evaluation
NUM_RUNS = len(RANDOM_STATE_PER_RUN) # 5  runs
NUM_SUBJECTS = 50
NUM_EXPERTS = 3
KERNEL = 20
EPOCHS = 200
BATCH_SIZE = 64
LR = 1e-3
N_FOLDS = 5
DROPOUT = 0.25
LOSS_FN = tf.keras.losses.CategoricalCrossentropy()

MODE = "all" # "all" -- 117 features, "stylus" -- 7 features, "hand" -- 110 features

OPT_WIN = 704
MIN_WIN = 64
MAX_WIN = 1774
MED_WIN = 896
WIN_STEP = 64

OPT_OVR = 0.9
MIN_OVR = 0.0
MAX_OVR = 1.0
OVR_STEP = 0.1

N_SAMPLES = 500 #samples from train and test to calculate Shapley values

headerPen = ["hour","min","sec","x","y","z","pressure", "azimuth", "altitude","proximity"]
headerHand = ["hour", "min", "sec", "handId",
              "x_thumb_dist", "y_thumb_dist", "z_thumb_dist",
              "x_thumb_intermed", "y_thumb_intermed", "z_thumb_intermed",
              "x_thumb_proxi", "y_thumb_proxi", "z_thumb_proxi",
              "x_thumb_metacarpal", "y_thumb_metacarpal", "z_thumb_metacarpal",
              "x_index_dist", "y_index_dist", "z_index_dist",
              "x_index_intermed", "y_index_intermed", "z_index_intermed",
              "x_index_proxi", "y_index_proxi", "z_index_proxi",
              "x_index_metacarpal", "y_index_metacarpal", "z_index_metacarpal",
              "x_index_metacarpal_base", "y_index_metacarpal_base", "z_index_metacarpal_base",
              "x_middle_dist", "y_middle_dist", "z_middle_dist",
              "x_middle_intermed", "y_middle_intermed", "z_middle_intermed",
              "x_middle_proxi", "y_middle_proxi", "z_middle_proxi",
              "x_middle_metacarpal", "y_middle_metacarpal", "z_middle_metacarpal",
              "x_middle_metacarpal_base", "y_middle_metacarpal_base", "z_middle_metacarpal_base",
              "x_ring_dist", "y_ring_dist", "z_ring_dist",
              "x_ring_intermed", "y_ring_intermed", "z_ring_intermed",
              "x_ring_proxi", "y_ring_proxi", "z_ring_proxi",
              "x_ring_metacarpal", "y_ring_metacarpal", "z_ring_metacarpal",
              "x_ring_metacarpal_base", "y_ring_metacarpal_base", "z_ring_metacarpal_base",
              "x_pinky_dist", "y_pinky_dist", "z_pinky_dist",
              "x_pinky_intermed", "y_pinky_intermed", "z_pinky_intermed",
              "x_pinky_proxi", "y_pinky_proxi", "z_pinky_proxi",
              "x_pinky_metacarpal", "y_pinky_metacarpal", "z_pinky_metacarpal",
              "x_pinky_metacarpal_base", "y_pinky_metacarpal_base", "z_pinky_metacarpal_base",
              "handCenter_x", "handCenter_y", "handCenter_z",
              "handSpeed_x", "handSpeed_y", "handSpeed_z",
              "handWidth", "pitch", "yaw", "roll", 'handPinchStrength',
              'handPinchDistance',
              'handPinchPosition_x', 'handPinchPosition_y', 'handPinchPosition_z',
              'handPredictedPinchPosition_x', 'handPredictedPinchPosition_y',
              'handPredictedPinchPosition_z',
              "handWristPosition_x", "handWristPosition_y", "handWristPosition_z",
              "handPalmNormal_x", "handPalmNormal_y", "handPalmNormal_z",
              "handGrabAngle", "handGrabStrength",
              "rotationOfHand_x", "rotationOfHand_y", "rotationOfHand_z", "rotationOfHand_w",
              "handArmLength", "handArmWidth",
              "elbowPosition_x", "elbowPosition_y", "elbowPosition_z",
              "handArmCenter_x", "handArmCenter_y", "handArmCenter_z",
              "confidence", "lifetimeOfThisHandObject"
              ]
features_117=[  "pressure",
                "azimuth",
                "altitude",
                "x",
                "y",
                "z",
                "proximity",
                "x_thumb_dist",
                "y_thumb_dist",
                "z_thumb_dist",
                "x_thumb_intermed",
                "y_thumb_intermed",
                "z_thumb_intermed",
                "x_thumb_proxi",
                "y_thumb_proxi",
                "z_thumb_proxi",
                "x_thumb_metacarpal",
                "y_thumb_metacarpal",
                "z_thumb_metacarpal",
                "x_index_dist",
                "y_index_dist",
                "z_index_dist",
                "x_index_intermed",
                "y_index_intermed",
                "z_index_intermed",
                "x_index_proxi",
                "y_index_proxi",
                "z_index_proxi",
                "x_index_metacarpal",
                "y_index_metacarpal",
                "z_index_metacarpal",
                "x_index_metacarpal_base",
                "y_index_metacarpal_base",
                "z_index_metacarpal_base",
                "x_middle_dist",
                "y_middle_dist",
                "z_middle_dist",
                "x_middle_intermed",
                "y_middle_intermed",
                "z_middle_intermed",
                "x_middle_proxi",
                "y_middle_proxi",
                "z_middle_proxi",
                "x_middle_metacarpal",
                "y_middle_metacarpal",
                "z_middle_metacarpal",
                "x_middle_metacarpal_base",
                "y_middle_metacarpal_base",
                "z_middle_metacarpal_base",
                "x_ring_dist",
                "y_ring_dist",
                "z_ring_dist",
                "x_ring_intermed",
                "y_ring_intermed",
                "z_ring_intermed",
                "x_ring_proxi",
                "y_ring_proxi",
                "z_ring_proxi",
                "x_ring_metacarpal",
                "y_ring_metacarpal",
                "z_ring_metacarpal",
                "x_ring_metacarpal_base",
                "y_ring_metacarpal_base",
                "z_ring_metacarpal_base",
                "x_pinky_dist",
                "y_pinky_dist",
                "z_pinky_dist",
                "x_pinky_intermed",
                "y_pinky_intermed",
                "z_pinky_intermed",
                "x_pinky_proxi",
                "y_pinky_proxi",
                "z_pinky_proxi",
                "x_pinky_metacarpal",
                "y_pinky_metacarpal",
                "z_pinky_metacarpal",
                "x_pinky_metacarpal_base",
                "y_pinky_metacarpal_base",
                "z_pinky_metacarpal_base",
                "handCenter_x",
                "handCenter_y",
                "handCenter_z",
                "handSpeed_x",
                "handSpeed_y",
                "handSpeed_z",
                "handWidth",
                "pitch",
                "yaw",
                "roll",
                "handPinchStrength",
                "handPinchDistance",
                "handPinchPosition_x",
                "handPinchPosition_y",
                "handPinchPosition_z",
                "handPredictedPinchPosition_x",
                "handPredictedPinchPosition_y",
                "handPredictedPinchPosition_z",
                "handWristPosition_x",
                "handWristPosition_y",
                "handWristPosition_z",
                "handPalmNormal_x",
                "handPalmNormal_y",
                "handPalmNormal_z",
                "handGrabAngle",
                "handGrabStrength",
                "rotationOfHand_x",
                "rotationOfHand_y",
                "rotationOfHand_z",
                "rotationOfHand_w",
                "handArmLength",
                "handArmWidth",
                "elbowPosition_x",
                "elbowPosition_y",
                "elbowPosition_z",
                "handArmCenter_x",
                "handArmCenter_y",
                "handArmCenter_z"]